# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
parameters:
- name: myVar
  type: string
  default: Hello world


pool:
  vmImage: ubuntu-latest

steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
- script: |
     echo ${{parameters.myVar}}
  displayName: Outputs Initial value
- script: |
    echo "##vso[task.setvariable variable=myVar;isOutput=true]Hello shravani"
  name: setVar
  displayName: Outputs new value
 
- script: |
    echo $(setVar.myVar)
  name: useVar
  displayName: Outputs new value
  